<?php

namespace AppBundle\Entity\Api;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr as Expr;
use Doctrine\ORM\AbstractQuery;

/**
 * PartieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartieRepository extends EntityRepository
{
    public function QueryParties($id = null)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->select('p,u')
            ->leftJoin('p.joueur', 'u', Expr\Join::WITH)
            ->orderBy('p.id', 'DESC')
        ;
        if($id != null){
            $qb->where('p.id = :id')
                ->setParameters([
                    ':id' => $id,
                ])
            ;
        }
        return null === $id
            ? $qb->getQuery()->getArrayResult()
            : $qb->getQuery()->getSingleResult(AbstractQuery::HYDRATE_ARRAY);
    }


    public function AllPartiesUser($token,$sort = false)
    {
        $parties = $this->QueryParties();
        /** @var Partie $partie */
        $start = [];
        $inProgress = [];
        $done = [];

        $prties = [];

        foreach($parties as $partie){
            /** @var User $joueur */
            foreach($partie['joueur'] as $joueur){
                if($joueur['token'] == $token) {
                    if ($sort) {
                        switch ($partie['etat']) {
                            case Partie::ETAT_DEBUT :
                                array_push($start, $partie);
                                break;
                            case Partie::ETAT_ENCOURS :
                                array_push($inProgress, $partie);
                                break;
                            case Partie::ETAT_FIN :
                                array_push($done, $partie);
                        }
                    }else{
                        array_push($prties,$partie);
                    }
                }
            }
        }
        if ($sort) {
            return [
                'play' => true,
                'start' => $start,
                'inProgress' => $inProgress,
                'done' => $done
            ];
        }else{
            return $prties;
        }
    }
}
