<?php

namespace AppBundle\Entity\Api;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr as Expr;
use Doctrine\ORM\AbstractQuery;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{

    public function findCatchThemAll($id = null)
    {
        $qb = $this->createQueryBuilder('q');
        $qb->select('q,c')
            ->leftJoin('q.categorie','c', Expr\Join::WITH)
            ->orderBy('q.id', 'DESC')
        ;
        if($id != null){
            $qb->where('q.id = :id')
                ->setParameters([
                    ':id' => $id,
                ])
            ;
        }
        return null === $id
            ? $qb->getQuery()->getArrayResult()
            : $qb->getQuery()->getSingleResult(AbstractQuery::HYDRATE_ARRAY);
    }

   /* public function QuestionNonValider()
    {
        $qb = $this->createQueryBuilder('q');
        $qb->select('q.id,q.nom')
            ->where('q.active = false')
        ;
        $questions= $qb->getQuery()->getSingleResult(AbstractQuery::HYDRATE_ARRAY);
        if ($questions != null){
            return[
                'questions' => $questions
            ];
        }else{
            return[
                'questions' => null
            ];
        }

    }*/

}
